table con_fallasEquipos
	lineageTag: b9eb2b01-56b7-4a84-8571-c1f93b0fcace

	measure 'MTBF (dias)' =
			
			VAR FechaCorte = TODAY()
			VAR Inicio = FechaCorte - 365
			VAR NumFallas =
			    CALCULATE(
			        DISTINCTCOUNT('con_fallasEquipos'[numDoc]),
			        REMOVEFILTERS('Dim_Fecha'),
			        REMOVEFILTERS('con_fallasEquipos'[FechaParada]),
			        REMOVEFILTERS('LocalDateTable_a3bf2546-fc06-4bcd-a44d-428fb5805a42'),
			        'con_fallasEquipos'[Fechafalla] >= Inicio,
			        'con_fallasEquipos'[Fechafalla] <= FechaCorte
			    )
			RETURN
			    DIVIDE(360, NumFallas + 1)
		formatString: 0.0" días"
		lineageTag: 77bb24e0-0dcd-4729-8ac1-01f02f205264

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MTTR Sin Partes (hrs)' =
			
			AVERAGEX(
			    FILTER(
			        'con_fallasEquipos',
			        'con_fallasEquipos'[tieneRequisicion] = 0
			    ),
			    'con_fallasEquipos'[HorasParada]
			)
		formatString: 0.0" días"
		lineageTag: c040e1ae-eb39-4a29-a5fe-dcde4c8599de

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ETTR (dias)' =
			
			AVERAGEX(
			    FILTER(
			        'con_fallasEquipos',
			        NOT ISBLANK('con_fallasEquipos'[FechaReparacion]) &&
			        NOT ISBLANK('con_fallasEquipos'[Fechafalla])
			    ),
			    DATEDIFF('con_fallasEquipos'[Fechafalla], 'con_fallasEquipos'[FechaReparacion], DAY)
			)
		formatString: 0.0" días"
		lineageTag: 4e288335-5aee-4f5c-9761-9ec4062dfc07

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'UPTIME %' =
			
			DIVIDE(
			    360 - [Dias Fuera de Servicio],
			    360
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 2db00436-1756-448f-b881-b219410ddb01

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dias Fuera de Servicio' = SUM('con_fallasEquipos'[HorasParada]) / 24
		formatString: 0.0
		lineageTag: 6d6f4882-21d8-467f-81f6-6aead399aa32

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MinFecha = MIN(con_fallasEquipos[Fechafalla])
		formatString: General Date
		lineageTag: 29ccd409-d544-43ee-a912-ab52d9b557b1

	measure MaxFecha = MAX(con_fallasEquipos[Fechafalla])
		formatString: General Date
		lineageTag: 4e8131c8-0747-486e-a51a-d01f98ff1398

	measure 'Preseleccion Periodo Parada' =
			
			VAR Periodo = SELECTEDVALUE('con_fallasEquipos'[Periodo Parada])
			VAR Inicio = FORMAT(EDATE(TODAY(), -11), "YYYY-MM")
			VAR Fin = FORMAT(TODAY(), "YYYY-MM")
			RETURN
			    Periodo >= Inicio && Periodo <= Fin
		lineageTag: 29990bc0-3925-40e2-9592-4030c4927e9c

	column equipo
		dataType: string
		lineageTag: 369a0d78-1d1a-4bdf-87f4-a46a7f12ccb8
		summarizeBy: none
		sourceColumn: equipo

		annotation SummarizationSetBy = Automatic

	column serial
		dataType: string
		lineageTag: cf09b85d-1b9d-4dbd-9803-0fa65228b26b
		summarizeBy: none
		sourceColumn: serial

		annotation SummarizationSetBy = Automatic

	column motivoservicio
		dataType: string
		lineageTag: 593753af-e9fd-4545-bc82-be518644a63e
		summarizeBy: none
		sourceColumn: motivoservicio

		annotation SummarizationSetBy = Automatic

	column Fechafalla
		dataType: dateTime
		formatString: Long Date
		lineageTag: ac75792b-cefd-4ced-8bec-a7acb7e17db2
		summarizeBy: none
		sourceColumn: Fechafalla

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column FechaParada
		dataType: dateTime
		formatString: General Date
		lineageTag: 3d170f72-58f8-4f8e-a347-538b3cefa7fa
		summarizeBy: none
		sourceColumn: FechaParada

		variation Variación
			isDefault
			relationship: 5640ce27-5a4e-41f7-85ef-5473f89b0667
			defaultHierarchy: LocalDateTable_a3bf2546-fc06-4bcd-a44d-428fb5805a42.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column FechaReparacion
		dataType: dateTime
		formatString: General Date
		lineageTag: bcdfe078-624c-4f3b-8ffe-63a25ebf70fb
		summarizeBy: none
		sourceColumn: FechaReparacion

		variation Variación
			isDefault
			relationship: 7bab45e7-1779-4da7-92f1-6e330791297b
			defaultHierarchy: LocalDateTable_ac37f0e6-0bb3-43fe-af3d-b1640dafc5e2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column marca
		dataType: string
		lineageTag: 81bfc619-f909-4925-8fb9-a4ed495c61d9
		summarizeBy: none
		sourceColumn: marca

		annotation SummarizationSetBy = Automatic

	column idOT
		dataType: int64
		formatString: 0
		lineageTag: abc87c40-31c1-4270-936f-dfe36c744ba3
		summarizeBy: sum
		sourceColumn: idOT

		annotation SummarizationSetBy = Automatic

	column subfamilia
		dataType: string
		lineageTag: 8a53fe0a-44da-4555-baf3-0819fd64b233
		summarizeBy: none
		sourceColumn: subfamilia

		annotation SummarizationSetBy = Automatic

	column numOTT
		dataType: int64
		formatString: 0
		lineageTag: ba6bd095-b058-4ab9-b7bb-431f6a5cd1e3
		summarizeBy: sum
		sourceColumn: numOTT

		annotation SummarizationSetBy = Automatic

	column cliente
		dataType: string
		lineageTag: 477b11af-0ca2-44e4-a95e-045f42feaaa0
		summarizeBy: none
		sourceColumn: cliente

		annotation SummarizationSetBy = Automatic

	column familia
		dataType: string
		lineageTag: 47aabf49-b6a4-4102-85d7-d639f4350b1e
		summarizeBy: none
		sourceColumn: familia

		annotation SummarizationSetBy = Automatic

	column 'Periodo Parada' = FORMAT('con_fallasEquipos'[FechaParada], "YYYY-MM")
		dataType: string
		lineageTag: c3e38446-302d-4209-92a1-92ce1f4ed8e0
		summarizeBy: none

	column idPadre
		dataType: int64
		formatString: 0
		lineageTag: 1dfa5c8a-ca20-45b7-b09c-9c96bd1abbd4
		summarizeBy: sum
		sourceColumn: idPadre

		annotation SummarizationSetBy = Automatic

	column numDoc
		dataType: int64
		formatString: 0
		lineageTag: 7a3466d0-0531-45c0-bc25-fd4e67d49783
		summarizeBy: sum
		sourceColumn: numDoc

		annotation SummarizationSetBy = Automatic

	column numSOL
		dataType: int64
		formatString: 0
		lineageTag: 92e5c786-e111-420c-a8e8-26959f830dea
		summarizeBy: sum
		sourceColumn: numSOL

		annotation SummarizationSetBy = Automatic

	column HorasParada
		dataType: double
		lineageTag: 95eb07b7-539a-48f4-92e4-600b3a97ee85
		summarizeBy: sum
		sourceColumn: HorasParada

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tieneRequisicion
		dataType: int64
		formatString: 0
		lineageTag: 6fbbaaf8-ba71-45b7-b6e3-cb57c91d441c
		summarizeBy: sum
		sourceColumn: tieneRequisicion

		annotation SummarizationSetBy = Automatic

	partition con_fallasEquipos = m
		mode: import
		source =
				let
				    Origen = Sql.Database("158.69.115.221:13001", "wh_impulmedicos", [Query="SELECT * FROM v_ind_fallas"]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Fechafalla", type date}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

