table Metas
	lineageTag: 04944223-AD3E-49AC-ADDB-E92BF2B47A56

	measure 'Meta Efectividad Remota' = AVERAGE(Metas[Efectividad Remota])
		lineageTag: 8AB9852C-3518-433F-B646-7C3B35756D45

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Color Fondo Efectividad Remota' = IF ( [%EfectREM] < [Meta Efectividad Remota], "#FF0000", "#00B050" )
		lineageTag: 1886B266-7169-490E-B37C-FB0A562EF3F3

	measure 'Meta MTTR SP' = AVERAGE(Metas[MTTR SP])
		lineageTag: c45deea1-4d80-4266-b63d-29074b0808ce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta Response Time' = AVERAGE(Metas[RT Remoto])
		lineageTag: 64440A2E-AFD3-441F-84D7-5D8C0633C94D

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta RT Sitio' = AVERAGE(Metas[RT Sitio])
		lineageTag: D0F0C0E6-F6A3-4721-AFC1-FA8954E50D1C

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Color MTTR SP' = IF ( [MTTR Sin Partes (hrs)] <= [Meta MTTR SP], "#2E8B57", "#D64550" )
		lineageTag: b658fb04-9874-43e8-810a-a534b6df2225

	measure 'Etiqueta MTTR SP' = "MTTR SP (< " & FORMAT ( [Meta MTTR SP], "0.#" ) & " hrs)"
		lineageTag: 18cbab86-70ec-4cef-8973-17e0ec406ac5

	column MES
		dataType: string
		lineageTag: 3111C4BC-3408-4852-9319-43DB8B1A66A4
		summarizeBy: none
		sourceColumn: MES

		annotation SummarizationSetBy = Automatic

	column FAMILIA
		dataType: string
		lineageTag: BA326EB9-2B58-415F-9CE6-BF0DA731932D
		summarizeBy: none
		sourceColumn: FAMILIA

		annotation SummarizationSetBy = Automatic

	column 'Efectividad Remota'
		dataType: double
		lineageTag: ed5584ea-a9a4-45c1-9e98-65e03c7a8f4f
		summarizeBy: sum
		sourceColumn: Efectividad Remota

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'MTTR SP'
		dataType: double
		lineageTag: a95e4de8-ee56-44ed-8c27-9c6e24acd9fc
		summarizeBy: none
		sourceColumn: MTTR SP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'RT Remoto'
		dataType: double
		lineageTag: D7928572-4B9F-4E23-8292-DA61BD1ABCE3
		summarizeBy: none
		sourceColumn: RT Remoto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'RT Sitio'
		dataType: double
		lineageTag: 89F91973-1F15-46B8-B604-683D32741B21
		summarizeBy: none
		sourceColumn: RT Sitio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Metas = m
		mode: import
		source =
				let
				    Origen = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1GE1gPbQNrcap7dwGmaI8tRY2R9cVzCKPsoi03CCd6Bk/edit?gid=1247000452#gid=1247000452"),
				    Metas_Table = Origen{[name="Metas",ItemKind="Table"]}[Data],
				    EsGenerico = List.AnyTrue(List.Transform(Table.ColumnNames(Metas_Table), each Text.StartsWith(_, "Column"))),
				    ConEncabezados = if EsGenerico then Table.PromoteHeaders(Metas_Table, [PromoteAllScalars=true]) else Metas_Table,
				    NombresLimpios = Table.TransformColumnNames(ConEncabezados, Text.Trim),
				    Efectividad = Table.TransformColumns(NombresLimpios, {{"Efectividad Remota", each Number.FromText(Text.Replace(Text.Trim(Text.From(_)), "%", "")) / 100, type number}}),
				    ConMTTR = if Table.HasColumns(Efectividad, "MTTR SP") then Table.TransformColumns(Efectividad, {{"MTTR SP", each try Number.FromText(Text.Trim(Text.From(_))) otherwise null, type number}}) else Table.AddColumn(Efectividad, "MTTR SP", each null, type number),
				    ConRT = if Table.HasColumns(ConMTTR, "RT Remoto") then Table.TransformColumns(ConMTTR, {{"RT Remoto", each try Number.FromText(Text.Trim(Text.From(_))) otherwise null, type number}}) else Table.AddColumn(ConMTTR, "RT Remoto", each null, type number),
				    ConSitio = if Table.HasColumns(ConRT, "RT Sitio") then Table.TransformColumns(ConRT, {{"RT Sitio", each try Number.FromText(Text.Trim(Text.From(_))) otherwise null, type number}}) else Table.AddColumn(ConRT, "RT Sitio", each null, type number),
				    Tipos = Table.TransformColumnTypes(ConSitio, {{"MES", type text}, {"FAMILIA", type text}}),
				    Seleccion = Table.SelectColumns(Tipos, {"MES", "FAMILIA", "Efectividad Remota", "MTTR SP", "RT Remoto", "RT Sitio"})
				in
				    Seleccion

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

