table Metas
	lineageTag: 04944223-AD3E-49AC-ADDB-E92BF2B47A56

	measure 'Meta Efectividad Remota' = AVERAGE(Metas[Efectividad Remota])
		lineageTag: 8AB9852C-3518-433F-B646-7C3B35756D45

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Color Fondo Efectividad Remota' = IF ( [%EfectREM] < [Meta Efectividad Remota], "#FF0000", "#00B050" )
		lineageTag: 1886B266-7169-490E-B37C-FB0A562EF3F3

	measure 'Meta MTTR SP' = AVERAGE(Metas[MTTR SP])
		lineageTag: c45deea1-4d80-4266-b63d-29074b0808ce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta Response Time' = AVERAGE(Metas[RT Remoto])
		lineageTag: 64440A2E-AFD3-441F-84D7-5D8C0633C94D

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta RT Sitio' = AVERAGE(Metas[RT Sitio])
		lineageTag: D0F0C0E6-F6A3-4721-AFC1-FA8954E50D1C

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta CR' = AVERAGE(Metas[CR Capture Rate])
		lineageTag: 24F903B8-8DA2-46AF-8B37-88E1B1DCFA7A

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta WC' = AVERAGE(Metas[Warranty Conversion])
		lineageTag: 8E7B951E-4C6A-44BB-938C-5DF777C2ACB3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta WB' = AVERAGE(Metas[Win Back])
		lineageTag: 05D692ED-5F54-477D-A165-43788EE7E586

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Meta Cobertura IB' = AVERAGE(Metas[Cobertura IB])
		lineageTag: F8E72392-940C-42C2-BBAC-97AD7493B787

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Color MTTR SP' = IF ( [MTTR Sin Partes (hrs)] <= [Meta MTTR SP], "#2E8B57", "#D64550" )
		lineageTag: b658fb04-9874-43e8-810a-a534b6df2225

	measure 'Etiqueta MTTR SP' = "MTTR SP (< " & FORMAT ( [Meta MTTR SP], "0.#" ) & " hrs)"
		lineageTag: 18cbab86-70ec-4cef-8973-17e0ec406ac5

	column MES
		dataType: string
		lineageTag: 3111C4BC-3408-4852-9319-43DB8B1A66A4
		summarizeBy: none
		sourceColumn: MES

		annotation SummarizationSetBy = Automatic

	column FAMILIA
		dataType: string
		lineageTag: BA326EB9-2B58-415F-9CE6-BF0DA731932D
		summarizeBy: none
		sourceColumn: FAMILIA

		annotation SummarizationSetBy = Automatic

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 7EF2B26F-06F4-48EE-9AC0-785A309F0C8D
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semestre
		dataType: string
		lineageTag: 94A58BA8-5D82-446C-ABD4-D18D9DD81BCB
		summarizeBy: none
		sourceColumn: Semestre

		annotation SummarizationSetBy = Automatic

	column Clave
		dataType: string
		lineageTag: 85D987E7-0999-41CC-A00B-060E084C17E0
		summarizeBy: none
		sourceColumn: Clave

		annotation SummarizationSetBy = Automatic

	column 'Efectividad Remota'
		dataType: double
		lineageTag: ed5584ea-a9a4-45c1-9e98-65e03c7a8f4f
		summarizeBy: sum
		sourceColumn: Efectividad Remota

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'MTTR SP'
		dataType: double
		lineageTag: a95e4de8-ee56-44ed-8c27-9c6e24acd9fc
		summarizeBy: none
		sourceColumn: MTTR SP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'RT Remoto'
		dataType: double
		lineageTag: D7928572-4B9F-4E23-8292-DA61BD1ABCE3
		summarizeBy: none
		sourceColumn: RT Remoto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'RT Sitio'
		dataType: double
		lineageTag: 89F91973-1F15-46B8-B604-683D32741B21
		summarizeBy: none
		sourceColumn: RT Sitio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'CR Capture Rate'
		dataType: double
		lineageTag: 72AD5804-DDA7-4C08-A1CE-26B5D5D2B622
		summarizeBy: none
		sourceColumn: CR Capture Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Warranty Conversion'
		dataType: double
		lineageTag: 2E3EBA63-48FF-4FBD-82FA-3675119CD85F
		summarizeBy: none
		sourceColumn: Warranty Conversion

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Win Back'
		dataType: double
		lineageTag: 3E757CD4-A8E8-4FDE-81A1-CE0FE5ABD1A8
		summarizeBy: none
		sourceColumn: Win Back

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cobertura IB'
		dataType: double
		lineageTag: 8196B9C2-F7E1-470D-B1C2-91D44C1DB76A
		summarizeBy: none
		sourceColumn: Cobertura IB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Metas = m
		mode: import
		source =
				let
				    Origen = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1GE1gPbQNrcap7dwGmaI8tRY2R9cVzCKPsoi03CCd6Bk/edit?gid=1247000452#gid=1247000452"),
				    Metas_Table = Origen{[name="Metas",ItemKind="Table"]}[Data],
				    EsGenerico = List.AnyTrue(List.Transform(Table.ColumnNames(Metas_Table), each Text.StartsWith(_, "Column"))),
				    ConEncabezados = if EsGenerico then Table.PromoteHeaders(Metas_Table, [PromoteAllScalars=true]) else Metas_Table,
				    NombresLimpios = Table.TransformColumnNames(ConEncabezados, Text.Trim),
				    Pct = (v) => let t = Text.Trim(Text.From(v)) in if Text.Contains(t, "%") then (try Number.FromText(Text.Replace(t, "%", "")) otherwise null) / 100 else (try Number.FromText(t) otherwise null),
				    Num = (v) => try Number.FromText(Text.Trim(Text.From(v))) otherwise null,
				    Conv = (tbl, col, fn) => if Table.HasColumns(tbl, col) then Table.TransformColumns(tbl, {{col, fn, type number}}) else Table.AddColumn(tbl, col, each null, type number),
				    C1 = Conv(NombresLimpios, "Efectividad Remota", Pct),
				    C2 = Conv(C1, "MTTR SP", Num),
				    C3 = Conv(C2, "RT Remoto", Num),
				    C4 = Conv(C3, "RT Sitio", Num),
				    C5 = Conv(C4, "CR Capture Rate", Pct),
				    C6 = Conv(C5, "Warranty Conversion", Pct),
				    C7 = Conv(C6, "Win Back", Pct),
				    C8 = Conv(C7, "Cobertura IB", Pct),
				    #"Año" = Table.AddColumn(C8, "Año", each try Number.FromText(Text.Start(Text.Trim(Text.From([MES])), 4)) otherwise null, Int64.Type),
				    #"Semestre" = Table.AddColumn(#"Año", "Semestre", each Text.AfterDelimiter(Text.Trim(Text.From([MES])), "-"), type text),
				    #"Clave" = Table.AddColumn(#"Semestre", "Clave", each Text.Trim(Text.From([FAMILIA])) & "|" & Text.From([Año]) & "-" & [Semestre], type text),
				    Tipos = Table.TransformColumnTypes(#"Clave", {{"MES", type text}, {"FAMILIA", type text}}),
				    Seleccion = Table.SelectColumns(Tipos, {"MES", "FAMILIA", "Año", "Semestre", "Clave", "Efectividad Remota", "MTTR SP", "RT Remoto", "RT Sitio", "CR Capture Rate", "Warranty Conversion", "Win Back", "Cobertura IB"})
				in
				    Seleccion

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación
